import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles(theme => ({
    root: {
      display: 'flex',
      padding: theme.spacing(10, 0),
      marginBottom: 400,
    },
    avatar: {
      width:25,
      height: 25,
      display:'flex',
      marginRight: 20,
    },
    icon: {
      color: theme.palette.text.primary,
      marginRight: theme.spacing(2),
    },
    title: {
      margin: theme.spacing(3, 0),
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    box:{
      boxSizing: 'border-box',
      margin: '0px 0px 18px',
      minWidth: '0px',
      display: 'flex',
      '-webkit-box-pack': 'justify',
      'justify-content': 'space-between',
      '-webkit-box-align': 'center',
      alignItems: 'center',
    },
    auctionBox:{
      boxSizing: 'border-box',
      margin: '0px 0px 48px',
      minWidth: '0px',
      padding:0,
      fontSize: '30px'
    },
    headerNft: {
      marginRight: '10px',
      color: theme.palette.type==="light" ? 'black' : 'white',
      fontSize: '40px',
      lineHeight: '48px',
      overflow: 'hidden',
      wordBreak: 'break-word',
      textOverflow: 'ellipsis',
      display: '-webkit-box',
      '-webkit-line-clamp': 2,
      '-webkit-box-orient': 'vertical',
      flex: '1 1 0%',
      textTransform: 'capitalize',
    },
    tag: {
      display: 'flex',
      alignItems: 'center',
    },
    profile: {
      display: 'flex',
    },
    row: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: theme.spacing(1, 0),
    },
    media:{
    },
    info:{

    },
    address:{
      boxSizing: 'border-box',
      margin: 0,
      minWidth: 0,
      fontSize: '12px',
      linHeight: '16px',
      color: theme.palette.text.primary,
      fontWeight: 500,
    },
    category:{
      fontWeight: 'bold',
    },
    contract:{
        marginTop : theme.spacing(4),
        display: 'flex',
        flexDirection: 'column',
    },
    description: {
      paddingTop: theme.spacing(6),
      color : theme.palette.text.primary,
    },
    addressTitle:{
      boxSizing: 'border-box',
      minWidth: 0,
      fontWeight: 400,
      fontSize: '12px',
      lineHeight: '16px',
      color: theme.palette.type==="light" ? 'black' : 'white',
    },
    bid:{
      display: 'flex',
      alignItems:'center',
      justifyContent: 'space-between',
      margin: '0 0 24px',
      boxSizing: 'border-box',
    },
    bidText:{
      boxSizing: 'border-box',
      margin: '0px 0px 4px',
      minWidth: 0,
      fontWeight: 500,
      fontSize: '14px',
      lineHeight: '20px',
      padding: 0,
      color:  theme.palette.type==="light" ? 'black' : 'white', 
    },
    price:{
      boxSizing: 'border-box',
      margin:'0px',
      minWidth: '0px',
      fontWeight: 600,
      fontSize: '28px',
      lineHeight: '36px',
      display: 'flex',
      '-webkit-box-align': 'center',
      alignItems: 'center',
      color: theme.palette.type==="light" ? 'black' : 'white',
    },
    realPrice: {
      boxSizing: 'border-box',
      margin: '0px 0px 0px 4px',
      minWidth: '0px',
      fontWeight: 400,
      fontSize: '14px',
      lineHeight: '20px',
      color: theme.palette.type==="light" ? 'rgb(112, 122, 138)' : 'white',
      paddingBottom: '4px',
    },
    priceLogo:{
      boxSizing: 'border-box',
      margin: '0px 8px 0px 0px',
      minWidth: '0px',
      maxWidth: '100%',
      width: '24px',
      height: '24px',
    },
    descriptionText:{
      fontSize: '14px',
      wordBreak: 'break-word',
      whiteSpace: 'pre-line',
      overflow: 'auto',
      maxHeight: 205,
      padding: 0,
    },
    owner:{
      display: 'flex',
      alignItems: 'center',
      fontSize: '12px',
      lineHeight: 1.5,
      color: theme.palette.text.primary,
    },
    creator:{
      display: 'flex',
      alignItems: 'center',
      fontSize: '12px',
      lineHeight: 1.5,
      color: theme.palette.text.primary,
      marginLeft: theme.spacing(3),
    },
    btnGroup: {
      '& .MuiButton-outlined': {
        border: `1px solid ${theme.palette.surface[3]}`,
      },
    },
    flex: {
      display:'flex',
      flexDirection:'column',
      alignItems: 'start',
      justifyContent : 'center'
    },
    flexRow:{
      display: 'flex',
    },
    auctionText:{
      boxSizing: 'border-box',
      margin: '0px',
      minWidth: '0px',
      fontWeight: 'bold',
      fontSize: '14px',
      lineHeight: '20px',
      textAlign: 'left',
    },
    buyNow:{
      boxSizing: 'border-box',
      margin: '0px',
      minWidth: '0px',
      display: 'flex',
      '-webkit-box-pack': 'justify',
      justifyContent: 'space-between',
      flexDirection: 'column',
    },
    buyNowBox:{
      boxSizing: 'border-box',
      margin: '0px',
      minWidth: '0px',
      width: '272px',
    },
    buyNowButton:{
      margin: '0px',
      minWidth: '0px',
      appearance: 'none',
      userSelect: 'none',
      cursor: 'pointer',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      display: 'inline-flex',
      '-webkit-box-align': 'center',
      alignItems: 'center',
      '-webkit-box-pack': 'center',
      justifyContent: 'center',
      boxSizing: 'border-box',
      fontFamily: 'inherit',
      textAlign: 'center',
      textDecoration: 'none',
      outline: 'none',
      fontWeight: 500,
      lineWeight: '20px',
      wordBreak:'keep-all',
      color: 'rgb(33, 40, 51)',
      borderRadius: '4px',
      padding: '4px 8px',
      minHeight: '24px',
      border: 'none',
      backgroundImage: 'linear-gradient(rgb(248, 209, 47) 0%, rgb(240, 185, 11) 100%)',
      width: '100%',
      height: '48px',
      fontSize: '16px',
    },
    timer:{
      display: 'flex',
      boxSizing: 'border-box',
      margin: '8px 0px 0px',
      minWidth: '0px',
      fontSize: '14px',
      '& div':{
        boxSizing: 'border-box',
        margin: '0px 6px 0px 0px',
        minWidth: '0px',
        textAlign: 'center',
        width: '24px',
        height: '24px',
        lineHeight: '24px',
        borderRadius:'4px',
        background: 'rgb(30, 35, 41)',
        color: 'rgb(255, 255, 255)',
        fontSize: '16px',
        fontWeight:'600',
      }
    },
    bold: {
      fontWeight: 'bold',
      margin: 0,
      padding: 0,
    },
    user:{
      display: 'flex',
      flexDirection: 'column',
      margin: 0,
      minWidth: 0,
      boxSizing: 'border-box',
    }
  }));

  export {useStyles};